import { FormField } from "./form.types";
import {
  DEPARTMENT_OPTIONS,
  ROLE_OPTIONS,
  LOCATION_OPTIONS,
  SALUTATION_OPTIONS,
  DESIGNATION_OPTIONS,
} from "./form.options";
export const employeeTableFields: FormField[] = [
  {
    name: "salutation",
    label: "Salutation",
    type: "select",
    options: SALUTATION_OPTIONS,
    required: true,
    validation: { required: "Salutation is required" },
  },
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    required: true,
    validation: { required: "First Name is required" },
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    required: true,
    validation: { required: "Last Name is required" },
  },
  {
    name: "emailId",
    label: "Email ID",
    type: "email",
    required: true,
    validation: { required: "Email is required", pattern: /^\S+@\S+$/i },
  },
  {
    name: "mobile",
    label: "Mobile Number",
    type: "text",
    required: true,
    validation: { required: "Mobile Number is required", pattern: /^[0-9]*$/ },
  },
  {
    name: "loginName",
    label: "Login Name",
    type: "text",
    required: true,
    validation: { required: "Login Name is required" },
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    required: true,
    validation: { required: "Password is required" },
  },
  {
    name: "roleId",
    label: "Role",
    type: "select",
    required: true,
    options: ROLE_OPTIONS,
    validation: { required: "Role is required" },
  },
  {
    name: "locationId",
    label: "Location",
    type: "select",
    required: true,
    options: LOCATION_OPTIONS,
    validation: { required: "Location is required" },
  },
  {
    name: "verticalId",
    label: "Vertical",
    type: "text",
    required: true,
    validation: { required: "Vertical is required" },
  },
  {
    name: "departmentId",
    label: "Department",
    type: "select",
    required: true,
    options: DEPARTMENT_OPTIONS,
    validation: { required: "Department is required" },
  },
  {
    name: "designationId",
    label: "Designation",
    type: "select", // Change type to select
    required: true,
    options: DESIGNATION_OPTIONS,
    validation: { required: "Designation is required" },
  },
  {
    name: "reportingUserId",
    label: "Reporting User ID",
    type: "text",
    required: true,
    validation: { required: "Reporting User ID is required" },
  },
  {
    name: "iirmEmpId",
    label: "IIRM Employee ID",
    type: "text",
    required: true,
    validation: { required: "IIRM Employee ID is required" },
  },
  {
    name: "iworkRoleId",
    label: "iWork Role ID",
    type: "text",
    required: true,
    validation: { required: "iWork Role ID is required" },
  },
];
